# Site settings
title: Subbly documentation
email: help@subbly.com
description: Description here
# description: > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

baseurl: "/documentation" # the subpath of your site, e.g. /blog/
url: "https://subbly.github.io/" # the base hostname & protocol for your site
# url: "http://doc.subbly.com" # the base hostname & protocol for your site
permalink: /updates/:year-:month-:day-:title

twitter_username: subbly
github_username:  subbly

# Build settings
markdown: kramdown

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
