var tree = [["Subbly","Subbly.html","",
                [["Api","Subbly\/Api.html","",
                [["Service","Subbly\/Api\/Service.html","",
                [["CartService","Subbly\/Api\/Service\/CartService.html"," < Service",
                [        ]],["Exception","Subbly\/Api\/Service\/Exception.html"," < Exception",
                [        ]],["OrderService","Subbly\/Api\/Service\/OrderService.html"," < Service",
                [        ]],["ProductService","Subbly\/Api\/Service\/ProductService.html"," < Service",
                [        ]],["Service","Subbly\/Api\/Service\/Service.html","",
                [        ]],["SettingService","Subbly\/Api\/Service\/SettingService.html"," < Service",
                [        ]],["UserService","Subbly\/Api\/Service\/UserService.html"," < Service",
                [        ]]        ]],["Api","Subbly\/Api\/Api.html","",
                [        ]],["Exception","Subbly\/Api\/Exception.html"," < Exception",
                [        ]]        ]],["CMS",,"",
                [["Controllers",,"",
                [["Api","Subbly\/CMS\/Controllers\/Api.html","",
                [["AuthController","Subbly\/CMS\/Controllers\/Api\/AuthController.html"," < BaseController",
                [        ]],["BaseController","Subbly\/CMS\/Controllers\/Api\/BaseController.html"," < Controller",
                [        ]],["OrdersController","Subbly\/CMS\/Controllers\/Api\/OrdersController.html"," < BaseController",
                [        ]],["ProductsController","Subbly\/CMS\/Controllers\/Api\/ProductsController.html"," < BaseController",
                [        ]],["SettingsController","Subbly\/CMS\/Controllers\/Api\/SettingsController.html"," < BaseController",
                [        ]],["UsersController","Subbly\/CMS\/Controllers\/Api\/UsersController.html"," < BaseController",
                [        ]],["WelcomeController","Subbly\/CMS\/Controllers\/Api\/WelcomeController.html"," < BaseController",
                [        ]]        ]]        ]]        ]],["Core","Subbly\/Core.html","",
                [["Installer","Subbly\/Core\/Installer.html","",
                [["Installer","Subbly\/Core\/Installer\/Installer.html","",
                [        ]]        ]],["Container","Subbly\/Core\/Container.html"," < Container",
                [        ]],["EventDispatcher","Subbly\/Core\/EventDispatcher.html"," < Dispatcher",
                [        ]]        ]],["Model","Subbly\/Model.html","",
                [["Concerns","Subbly\/Model\/Concerns.html","",
                [["AddressTrait","Subbly\/Model\/Concerns\/AddressTrait.html","",
                [        ]],["DefaultValues","Subbly\/Model\/Concerns\/DefaultValues.html","",
                [        ]],["SubblyModel","Subbly\/Model\/Concerns\/SubblyModel.html","",
                [        ]],["Validable","Subbly\/Model\/Concerns\/Validable.html","",
                [        ]]        ]],["Exception","Subbly\/Model\/Exception.html","",
                [["UnvalidModelException","Subbly\/Model\/Exception\/UnvalidModelException.html"," < Exception",
                [        ]]        ]],["Collection","Subbly\/Model\/Collection.html"," < Collection",
                [        ]],["ModelInterface","Subbly\/Model\/ModelInterface.html","",
                [        ]],["Order","Subbly\/Model\/Order.html"," < Model",
                [        ]],["OrderAddress","Subbly\/Model\/OrderAddress.html"," < Model",
                [        ]],["OrderProduct","Subbly\/Model\/OrderProduct.html"," < Model",
                [        ]],["Product","Subbly\/Model\/Product.html"," < Model",
                [        ]],["ProductCategory","Subbly\/Model\/ProductCategory.html"," < Model",
                [        ]],["ProductImage","Subbly\/Model\/ProductImage.html"," < Model",
                [        ]],["ProductOption","Subbly\/Model\/ProductOption.html"," < Model",
                [        ]],["Setting","Subbly\/Model\/Setting.html"," < Model",
                [        ]],["User","Subbly\/Model\/User.html"," < User",
                [        ]],["UserAddress","Subbly\/Model\/UserAddress.html"," < Model",
                [        ]]        ]],["Subbly","Subbly\/Subbly.html","",
                [        ]]        ]]        ]

